// Generated by gencpp from file weatherbotproject/WeatherServiceResponse.msg
// DO NOT EDIT!


#ifndef WEATHERBOTPROJECT_MESSAGE_WEATHERSERVICERESPONSE_H
#define WEATHERBOTPROJECT_MESSAGE_WEATHERSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace weatherbotproject
{
template <class ContainerAllocator>
struct WeatherServiceResponse_
{
  typedef WeatherServiceResponse_<ContainerAllocator> Type;

  WeatherServiceResponse_()
    : ok(0)  {
    }
  WeatherServiceResponse_(const ContainerAllocator& _alloc)
    : ok(0)  {
  (void)_alloc;
    }



   typedef uint32_t _ok_type;
  _ok_type ok;





  typedef boost::shared_ptr< ::weatherbotproject::WeatherServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::weatherbotproject::WeatherServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WeatherServiceResponse_

typedef ::weatherbotproject::WeatherServiceResponse_<std::allocator<void> > WeatherServiceResponse;

typedef boost::shared_ptr< ::weatherbotproject::WeatherServiceResponse > WeatherServiceResponsePtr;
typedef boost::shared_ptr< ::weatherbotproject::WeatherServiceResponse const> WeatherServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::weatherbotproject::WeatherServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::weatherbotproject::WeatherServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::weatherbotproject::WeatherServiceResponse_<ContainerAllocator1> & lhs, const ::weatherbotproject::WeatherServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ok == rhs.ok;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::weatherbotproject::WeatherServiceResponse_<ContainerAllocator1> & lhs, const ::weatherbotproject::WeatherServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace weatherbotproject

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::weatherbotproject::WeatherServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::weatherbotproject::WeatherServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::weatherbotproject::WeatherServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::weatherbotproject::WeatherServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::weatherbotproject::WeatherServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::weatherbotproject::WeatherServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::weatherbotproject::WeatherServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc98085824fd3dfdd9a20e11d08cfef6";
  }

  static const char* value(const ::weatherbotproject::WeatherServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc98085824fd3dfdULL;
  static const uint64_t static_value2 = 0xd9a20e11d08cfef6ULL;
};

template<class ContainerAllocator>
struct DataType< ::weatherbotproject::WeatherServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "weatherbotproject/WeatherServiceResponse";
  }

  static const char* value(const ::weatherbotproject::WeatherServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::weatherbotproject::WeatherServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 ok\n"
"\n"
;
  }

  static const char* value(const ::weatherbotproject::WeatherServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::weatherbotproject::WeatherServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WeatherServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::weatherbotproject::WeatherServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::weatherbotproject::WeatherServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "ok: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEATHERBOTPROJECT_MESSAGE_WEATHERSERVICERESPONSE_H
