// Generated by gencpp from file weatherbotproject/WeatherService.msg
// DO NOT EDIT!


#ifndef WEATHERBOTPROJECT_MESSAGE_WEATHERSERVICE_H
#define WEATHERBOTPROJECT_MESSAGE_WEATHERSERVICE_H

#include <ros/service_traits.h>


#include <weatherbotproject/WeatherServiceRequest.h>
#include <weatherbotproject/WeatherServiceResponse.h>


namespace weatherbotproject
{

struct WeatherService
{

typedef WeatherServiceRequest Request;
typedef WeatherServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WeatherService
} // namespace weatherbotproject


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::weatherbotproject::WeatherService > {
  static const char* value()
  {
    return "456b4033dd09be069e0eb63a859d7454";
  }

  static const char* value(const ::weatherbotproject::WeatherService&) { return value(); }
};

template<>
struct DataType< ::weatherbotproject::WeatherService > {
  static const char* value()
  {
    return "weatherbotproject/WeatherService";
  }

  static const char* value(const ::weatherbotproject::WeatherService&) { return value(); }
};


// service_traits::MD5Sum< ::weatherbotproject::WeatherServiceRequest> should match
// service_traits::MD5Sum< ::weatherbotproject::WeatherService >
template<>
struct MD5Sum< ::weatherbotproject::WeatherServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::weatherbotproject::WeatherService >::value();
  }
  static const char* value(const ::weatherbotproject::WeatherServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::weatherbotproject::WeatherServiceRequest> should match
// service_traits::DataType< ::weatherbotproject::WeatherService >
template<>
struct DataType< ::weatherbotproject::WeatherServiceRequest>
{
  static const char* value()
  {
    return DataType< ::weatherbotproject::WeatherService >::value();
  }
  static const char* value(const ::weatherbotproject::WeatherServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::weatherbotproject::WeatherServiceResponse> should match
// service_traits::MD5Sum< ::weatherbotproject::WeatherService >
template<>
struct MD5Sum< ::weatherbotproject::WeatherServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::weatherbotproject::WeatherService >::value();
  }
  static const char* value(const ::weatherbotproject::WeatherServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::weatherbotproject::WeatherServiceResponse> should match
// service_traits::DataType< ::weatherbotproject::WeatherService >
template<>
struct DataType< ::weatherbotproject::WeatherServiceResponse>
{
  static const char* value()
  {
    return DataType< ::weatherbotproject::WeatherService >::value();
  }
  static const char* value(const ::weatherbotproject::WeatherServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEATHERBOTPROJECT_MESSAGE_WEATHERSERVICE_H
